apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: backend-pvc 
  namespace: cloudbite-dev 
spec: 
  accessModes: 
    - ReadWriteOnce 
  resources: 
    requests: 
      storage: 2Gi
    limits: 
      storage: 3Gi
  storageClassName: standard
