apiVersion: v1 
kind: Secret 
metadata: 
  name: backend-secrets 
  namespace: cloudbite-dev 
type: Opaque
stringData: 
  JWT_SECRET: YOUR_JWT_SECRET_HERE
  SALT: YOUR_SALT_HERE
  STRIPE_SECRET_KEY: YOUR_STRIPE_SECRET_KEY_HERE
  MONGO_URL: YOUR_MONGO_URL_HERE

