apiVersion: v1 
kind: Secret 
metadata:
  name: mongodb-secret
  namespace: cloudbite-dev
type: Opaque 
stringData:
  MONGO_INITDB_ROOT_USERNAME: ADD_YOUR_USERNAME
  MONGO_INITDB_ROOT_PASSWORD: ADD_YOUR_PASSWORD