apiVersion: v1 
kind: Service 
metadata: 
  name: frontend-service 
  namespace: cloudbite-dev
  labels: 
    app: frontend 
    env: dev 
spec: 
  ports: 
    - port: 80
      targetPort: 80
      protocol: TCP
  selector: 
    app: frontend 
    env: dev 
