apiVersion: v1
kind: Namespace
metadata:
  name: cloudbite-prod
  labels:
    environment: production 
    app: cloudbite

---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudbite-staging
  labels:
    environment: staging
    app: cloudbite

---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudbite-dev
  labels:
    environment: development
    app: cloudbite
