apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
    env: dev
spec:
  replicas: {{ .Values.backend.replicas }}

  selector:
    matchLabels:
      app: backend
      env: dev

  template:
    metadata:
      labels:
        app: backend
        env: dev

    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: Always

          ports:
            - containerPort: {{ .Values.backend.service.port }}

          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: JWT_SECRET

            - name: SALT
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SALT

            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: STRIPE_SECRET_KEY

            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MONGO_URL

          volumeMounts:
            - name: backend-volume
              mountPath: /app/uploads

      volumes:
        - name: backend-volume
          persistentVolumeClaim:
            claimName: backend-pvc
