---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: cloudbite-dev
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgAluqNp9dK7B7L1J6ckTJDE/tGRW4wGcG4Pc7XklrUjBJdxJVdyk183uCu6lVpTUO0mrck1Tjvyal4ngKwGQWiD9JOpSjdL0aYfKSW7/huXEU7vro54wg6AWuBZWAPuiLaXB2qIcjYvST7INKwhB90myxuHnDy0Z7BkPPIyz2+QAD8+TkLityZN1uz/D4IYJA6Kz8qBDSOuvsjLOnutW8tT8xcqkggpUgNqDjMqO9yfJHu9C1WeN5is/VaEb6NEHhQmNwfdf8dpMCSTiRrfD0QmrnE5GpshkR3YLofKHwZraKYFeLi6tbu1MHP+RCMR9E7HLIpgZUc1Ipuwx0h0ZokY9371P2EhCNtfT8L1cwwezFRt0Ki7ciu+YFeYSozti/5c6lkwSwMbXbxuvAf8MApXMDqH6MSUu1WvlsKc57Xjhx1PlgLHyecYk2f7c824DuUKaig8bKaqUGR+iu8/BgFdm4a4q93HUhEo2/ez+6SFxTnX7sqlvtXTlkM4yx9tvKzUBuDN1WF8OJ8harexEvQ29qOCPpO2e+GVrdx7COL8diODXXc8MdStoHOunVaoAZCcucBE/vj1/chi58bGo7WgaoZ0/oSubx3CF5oky1VmMD7PbQB63Lv4bFZdAP5iVVdePVc3+CGWk/Yby1PLTR4T7YaR6l8Pu8gbhlP/55XDvcXbM2uQiWsChnuDVxU0sHc7Hwbbuy+sIdnCYqNdWnCI
    MONGO_INITDB_ROOT_USERNAME: AgCjTtvgMcTeNI9lPtxJu/EwnGr8ofPDqUZ+JfzAncRnnJ4xHPEzjiJbP5pohKb8ZGppcYiE1CLz1KJBI88lof12f8Xw6ks8jvUleRKGiMCp6dxR1h5gyeHKDQ7Z1YVAbJUSzyume5ZMqvwfD5wV5lY+fMba7evi4jY9H+pzVVTJHEizaCQXpqxJxKQ0tlwqRjnWTaENvEWLwdmtKRq6NcoTN+4N7v2tjvazfezB+n3ETeh3ZV+2+oRQZo1bPeYflohbgq7dmoXmjtc/wf9esdopHtKSNMJG5vQAdLTo3Er/3uCs7htbwhkWyPPFxq1xcb7jEnS02pUnEaGDvgdJl+9X4vBMMStuM0xEnIzRGo0WligBYehb7dJO0VEcp4nqFHNqP6WcdQIOvNJG+hYD5Q+zAw11hCypYvoWtRdWgp18S/wnMU+KL+X1eGuQrFgL4971ImvptQS5AXG8+kJ7N9UWE/4x3imaBWWC1UF8P1WZQ2aDq1H7pMiuXFbVDshllKcyyB7y4a41KUDJFGaRKwqIGJ5X4FcPjNfSpmdOjxA2S3G3pcP85eRVfmpfoVtpGCfY4jrZ+Ns+t/fGfTpa6NxkIiNL/Tr720UySosMZEUgfkfsmB/bU6j6VpNPjoC05TNE6CfvOTM27PfS1IJjbMCfQIIerpki4t9HdfkrH7cBlyz2/6pXCFfcozDjkst8djiOmkV3DgWDIabXr8RFiJL7qaS72bhVng==
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: cloudbite-dev
    type: Opaque
