---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: cloudbite-dev
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgCC3YJuXVPIBrHsf3vcYHkViOxuwXUvRkZ7JQlbeMCz0bDFoI05W8AJw4FvU+7gusCsGw88Y/GxKzhTJfEzSb74XO5bY/5hK69Jyz7GXpYpjyY/BU6Hto5xyJIkoor3e3SXRGgPOpxWSUxcT+JJL2IRoyUVGww9AkHoQ+cw0my17pACpbsvT9nnJDGVWo3Uj0bHF3BV3bgSIrOmHnOacQDYRX60Ze1NiRlKHI3WY0ad0bSlY7eX3hOOlnYxoBKOlQkNQUzDbc6UNDIXn1yhWoHeBmpU3bY8B4oBpK629ul6qQV0fP2myTq0j7Ogmmb4dcaRdruIMTGm4nAFKVmUVV9DONKDgcDKSDKSAissmkwZfzAn+Y40/ro86LksZ1usH8yU5FHFOr9KgDlpa4D65FZdKN8MQeVoOpvGsl31HjygIYkGCy1M5afyzgnmYPVcrzQGYSku937GEapOKpDi2o15+oEMxpSjLXa2VBUJFp05BogtX75FpCXrnmLrCigD7ZRZz7YKK0MixNW9iMtEBauutoukko489nILQb4iiMoBzWxL9Fe1mDLrcyNyF2eCflv2043awQ8TnLyjgvgVKQ6juGxkGznOI4hxNtusChFuiSo+so0PAhUyXwp1IRDdey3h4Bbqc58AWY2NDrjJ7Gcf/WMRk3ITiFaCRSp2dVr7ptlZiMQnYRx2crNYzuW016OQTTeHgC+c2EujNpVU4o0IeQ==
    MONGO_INITDB_ROOT_USERNAME: AgC3E89w97chEw+fx+oVoKrLN7p/IydwRn1MTQQNBGZzzi0S0eij9kd4MfKKdhLGSlhdB0v4/jyHOKMDX946QBEEkJhNQy6DnsJ9t3l30xxBYOItL78MOK11X3MUHmYzmjePgZXbVg4yBtu1Qg7N8esSRQJw2uf2TloGc3A1Sy4Je5Qc6/czy9oxBlQlMmhGg5XXq34BavJ5s1osFOXVEtsC7eMrclF2HJCL06YUDNvQqOiiwZ2TPNPR21gJtAtJ9XoxH2K6uyGYTMdRK32pSnEtnE3c4CQJjprhLP0IX7Ps1tSKUidI2L1KynB0z8+EHBafmMKQWsNTG1aZ8TaH8bNnxVbERDgwXvX0tLAv3z93PrnUeSyJM/f7iBDvDPOgkt7fzASWYu3LJh87UJckriKQNu1g7bbrypjPmVIhk/IhrcwdSsiRKJafejTNMrd2QeqtaL+qFzSHAvSjPG9Og5w7+TkI50GrtStqhRB218peioqyO0epKMTNgRp1qB9JIEKVijGieSFYXBjSXaYxaa6Th3scx7HfsRChzXDPJT4MNztXoaHKyJeSEv0EWXstXmIZOWJG0j7j8Sc3CYHOpGrm2qtXhgdVz0IfjSDiT9vMPtqQDWXBs0Gr/adcGHZWn42pVQsE8buZb5kuLs036ruV6LxI7R/XMZ/eo9fikg55OJ+MYqkW54WE+tTsRgmavsJzjC6xVc0z7Ww/iayN3HZUgJ1yYpxvOA==
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: cloudbite-dev
