apiVersion: argoproj.io/v1alpha1 
kind: Application 
metadata: 
  name: cloudbite-app 
  namespace: argocd
spec: 
  project: default 
  source: 
    repoURL: https://github.com/seela-2001/cloudBite 
    targetRevision: main 
    path: cloudbite-chart 
  destination: 
    server: https://kubernetes.default.svc
    namespace: cloudbite-dev
  syncPolicy: 
    automated: 
      selfHeal: true
      prune: true
