apiVersion: argoproj.io/v1alpha1 
kind: Application 
metadata: 
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=sohila12/cloudbite-backend,frontend=sohila12/cloudbite-frontend
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest
  name: cloudbite-app 
  namespace: argocd
spec: 
  project: default 
  source: 
    repoURL: https://github.com/seela-2001/cloudBite 
    targetRevision: main 
    path: cloudbite-chart 
  destination: 
    server: https://kubernetes.default.svc
    namespace: cloudbite-dev
  syncPolicy: 
    automated: 
      selfHeal: true
      prune: true
