backend:
  image:
    repository: sohila12/cloudbite-backend
    tag: 21c02c6e215e70d28e0be037c64f391ea844fdaa
  service:
    port: 4000
  replicas: 2

frontend:
  image:
    repository: sohila12/cloudbite-frontend
    tag: 21c02c6e215e70d28e0be037c64f391ea844fdaa
  service:
    port: 80
  replicas: 1

mongodb:
  image:
    repository: mongo
    tag: 21c02c6e215e70d28e0be037c64f391ea844fdaa
  service:
    port: 27017
  replicas: 1
  storage: 1Gi