backend:
  image:
    repository: sohila12/cloudbite-backend
    tag: e8b9f46aaa758f256f7b544b12f66841948da7dd
  service:
    port: 4000
  replicas: 2

frontend:
  image:
    repository: sohila12/cloudbite-frontend
    tag: e8b9f46aaa758f256f7b544b12f66841948da7dd
  service:
    port: 80
  replicas: 2

mongodb:
  image:
    repository: mongo
    tag: e8b9f46aaa758f256f7b544b12f66841948da7dd
  service:
    port: 27017
  replicas: 1
  storage: 1Gi